spring:
  banner:
    image:
      location: 'claspath:banner.txt'
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled:  ALWAYS

server:
  port: 8090

logging:
  file: logs/spring-boot-logging.log
  level:
    com:  debug
